Controller:
  model_structure: null
MFVI:
  hexa_rank: 150
  hexa_std: 1
  iterations: 3
  normalize_weight: true
  quad_rank: 150
  quad_std: 1
  tag_dim: 150
  use_hexalinear: false
  use_quadrilinear: false
  use_second_order: false
  use_third_order: false
  window_size: 1
ReinforcementTrainer:
  controller_learning_rate: 0.1
  controller_optimizer: SGD
  distill_mode: false
  optimizer: SGD
  sentence_level_batch: true
anneal_factor: 2
ast:
  Corpus: SEMEVAL16-TR:SEMEVAL16-ES:SEMEVAL16-NL:SEMEVAL16-EN:SEMEVAL16-RU
atis:
  Corpus: ATIS-EN:ATIS-TR:ATIS-HI
chunk:
  Corpus: CONLL_03:CONLL_03_GERMAN
embeddings:
  ELMoEmbeddings-0:
    options_file: /home/yongjiang.jy/.flair/embeddings/options262.json
    weight_file: /home/yongjiang.jy/.flair/embeddings/de_weights.hdf5
  FastCharacterEmbeddings:
    char_embedding_dim: 25
    hidden_size_char: 25
  FastWordEmbeddings-0:
    embeddings: de
    freeze: true
  FlairEmbeddings-0:
    model: de-forward
  FlairEmbeddings-1:
    model: de-backward
  FlairEmbeddings-2:
    model: multi-forward
  FlairEmbeddings-3:
    model: multi-backward
  TransformerWordEmbeddings-0:
    layers: '-1'
    model: /home/yongjiang.jy/.flair/embeddings/xlm-roberta-large-finetuned-conll03-german
    pooling_operation: first
  TransformerWordEmbeddings-1:
    layers: '-1'
    model: /home/yongjiang.jy/.flair/embeddings/de-bert_10epoch_32batch_0.00005lr_10000lrrate_de_monolingual_nocrf_fast_relearn_sentbatch_sentloss_finetune_saving_nodev_newner3/bert-base-german-cased
    pooling_operation: first
  TransformerWordEmbeddings-2:
    layers: '-1'
    model: /home/yongjiang.jy/.flair/embeddings/multi-bert_10epoch_32batch_0.00005lr_10000lrrate_de_monolingual_nocrf_fast_relearn_sentbatch_sentloss_finetune_saving_nodev_newner3/bert-base-multilingual-cased
    pooling_operation: first
interpolation: 0.5
is_teacher_list: true
model:
  FastSequenceTagger:
    crf_attention: false
    dropout: 0.0
    hidden_size: 800
    sentence_loss: true
    use_crf: true
model_name: de-xlmr-tuned_de-elmo_bert-task_multi-bert-task_word_origflair_mflair_char_30episode_300epoch_32batch_0.1lr_800hidden_de_monolingual_crf_fast_sqrtreward_reinforce_random_freeze_norelearn_sentbatch_0.5discount_5patience_nodev_newner6
ner:
  Corpus: CONLL_03_GERMAN_NEW
  professors:
    config/single-de-ner.yaml: CONLL_03_GERMAN
    config/single-en-ner.yaml: CONLL_03
    config/single-es-ner.yaml: CONLL_03_SPANISH
    config/single-nl-ner.yaml: CONLL_03_DUTCH
  tag_dictionary: resources/taggers/ner_tags.pkl
  teachers:
    ? config_gen/multi-bert_flair_word_char_charcnn_300epoch_32batch_0.1lr_256hidden_de_monolingual_crf_sentloss_10patience_fast_sentbatch_relearn_fasttext_freeze_nodev_panx_ner45.yaml
    : PANX-DE
    ? config_gen/multi-bert_flair_word_char_charcnn_300epoch_32batch_0.1lr_256hidden_es_monolingual_crf_sentloss_10patience_fast_sentbatch_relearn_fasttext_freeze_nodev_panx_ner45.yaml
    : PANX-ES
    ? config_gen/multi-bert_flair_word_char_charcnn_300epoch_32batch_0.1lr_256hidden_nl_monolingual_crf_sentloss_10patience_fast_sentbatch_relearn_fasttext_freeze_nodev_panx_ner44.yaml
    : PANX-NL
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_de_monolingual_crf_sentloss_10patience_baseline_fast_nodev_ner12.yaml
    : CONLL_03_GERMAN
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_en_monolingual_crf_sentloss_10patience_baseline_fast_nodev_ner11.yaml
    : CONLL_03
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_en_monolingual_crf_sentloss_10patience_baseline_fast_nodev_panx_ner8.yaml
    : PANX-EN
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_es_monolingual_crf_sentloss_10patience_baseline_fast_nodev_ner12.yaml
    : CONLL_03_SPANISH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_eu_monolingual_crf_sentloss_10patience_baseline_fast_nodev_panx_ner8.yaml
    : PANX-EU
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_fa_monolingual_crf_sentloss_10patience_baseline_fast_nodev_panx_ner8.yaml
    : PANX-FA
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_fr_monolingual_crf_sentloss_10patience_baseline_fast_nodev_panx_ner8.yaml
    : PANX-FR
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_he_monolingual_crf_sentloss_10patience_baseline_fast_nodev_panx_ner6.yaml
    : PANX-HE
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_id_monolingual_crf_sentloss_10patience_baseline_fast_nodev_panx_ner8.yaml
    : PANX-ID
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_nl_monolingual_crf_sentloss_10patience_baseline_fast_nodev_ner11.yaml
    : CONLL_03_DUTCH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_sl_monolingual_crf_sentloss_10patience_baseline_fast_nodev_panx_ner7.yaml
    : PANX-SL
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_ta_monolingual_crf_sentloss_10patience_baseline_fast_nodev_panx_ner6.yaml
    : PANX-TA
target_dir: resources/taggers/
targets: ner
teacher_annealing: false
train:
  controller_momentum: 0.9
  discount: 0.5
  learning_rate: 0.1
  max_episodes: 30
  max_epochs: 300
  max_epochs_without_improvement: 25
  mini_batch_size: 32
  monitor_test: false
  patience: 5
  random_search: true
  save_final_model: false
  sqrt_reward: true
  train_with_dev: false
  true_reshuffle: false
  use_warmup: false
trainer: ReinforcementTrainer
upos:
  Corpus: UD_GERMAN:UD_ENGLISH:UD_FRENCH:UD_ITALIAN:UD_DUTCH:UD_SPANISH:UD_PORTUGUESE:UD_JAPANESE
  UD_GERMAN:
    train_config: config/
  professors:
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_de_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_GERMAN
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_en_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos0.yaml
    : UD_ENGLISH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_es_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos0.yaml
    : UD_SPANISH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_fr_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_FRENCH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_it_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_ITALIAN
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_ja_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_JAPANESE
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_nl_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_DUTCH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_pt_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_PORTUGUESE
  tag_dictionary: resources/taggers/pos_tags.pkl
  teachers:
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_de_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_GERMAN
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_en_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos0.yaml
    : UD_ENGLISH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_es_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos0.yaml
    : UD_SPANISH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_fr_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_FRENCH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_it_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_ITALIAN
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_ja_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_JAPANESE
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_nl_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_DUTCH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_pt_monolingual_crf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_PORTUGUESE
