Controller:
  model_structure: null
ReinforcementTrainer:
  assign_doc_id: true
  controller_learning_rate: 0.1
  controller_optimizer: SGD
  distill_mode: false
  optimizer: SGD
  pretrained_file_dict:
    /home/yongjiang.jy/.flair/embeddings/bert-base-dutch-cased-finetuned-conll2002-ner: bert-base-dutch-cased-finetuned-conll2002-ner.hdf5
    /home/yongjiang.jy/.flair/embeddings/xlm-roberta-large-finetuned-conll02-dutch: xlm-roberta-large-finetuned-conll02-dutch.hdf5
    bert-base-multilingual-cased: bert-base-multilingual-cased.hdf5
  sentence_level_batch: true
anneal_factor: 2
embeddings:
  FastCharacterEmbeddings:
    char_embedding_dim: 25
    hidden_size_char: 25
  FastWordEmbeddings-0:
    embeddings: nl
    freeze: true
  FlairEmbeddings-0:
    model: en-forward
  FlairEmbeddings-1:
    model: en-backward
  FlairEmbeddings-2:
    model: multi-forward
  FlairEmbeddings-3:
    model: multi-backward
  TransformerWordEmbeddings-0:
    layers: '-1'
    model: xlm-roberta-large-finetuned-conll02-dutch
    pooling_operation: first
    embedding_name: /home/yongjiang.jy/.flair/embeddings/xlm-roberta-large-finetuned-conll02-dutch # DO NOT modify this when using the downloaded models. You can remove if you want to train the model
  TransformerWordEmbeddings-1:
    layers: -1,-2,-3,-4
    model: bert-base-dutch-cased-finetuned-conll2002-ner
    pooling_operation: first
    embedding_name: /home/yongjiang.jy/.flair/embeddings/bert-base-dutch-cased-finetuned-conll2002-ner # DO NOT modify this when using the downloaded models. You can remove if you want to train the model
  TransformerWordEmbeddings-2:
    layers: -1,-2,-3,-4
    model: bert-base-multilingual-cased
    pooling_operation: first
interpolation: 0.5
is_teacher_list: true
model:
  FastSequenceTagger:
    crf_attention: false
    dropout: 0.0
    hidden_size: 800
    sentence_loss: true
    use_crf: true
model_name: nl-xlmr-tuned-first-pred_nl-bert-tuned-four-first-pred_multi-bert-four-first-pred_word_en-flair_mflair_char_30episode_150epoch_32batch_0.1lr_800hidden_nl_monolingual_crf_fast_reinforce_freeze_norelearn_sentbatch_5patience_nodev_newner2
ner:
  Corpus: CONLL_03_DUTCH_NEW
  professors:
    config/single-de-ner.yaml: CONLL_03_GERMAN
    config/single-en-ner.yaml: CONLL_03
    config/single-es-ner.yaml: CONLL_03_SPANISH
    config/single-nl-ner.yaml: CONLL_03_DUTCH
  tag_dictionary: resources/taggers/ner_tags.pkl
target_dir: resources/taggers/
targets: ner
teacher_annealing: false
train:
  controller_momentum: 0.9
  learning_rate: 0.1
  max_episodes: 30
  max_epochs: 150
  max_epochs_without_improvement: 25
  mini_batch_size: 32
  monitor_test: false
  patience: 5
  save_final_model: false
  train_with_dev: false
  true_reshuffle: false
  use_warmup: false
trainer: ReinforcementTrainer
