ModelFinetuner:
  distill_mode: false
  sentence_level_batch: true
anneal_factor: 2
ast:
  Corpus: SEMEVAL15_RESTAURANT
atis:
  Corpus: ATIS-EN:ATIS-TR:ATIS-HI
chunk:
  Corpus: CONLL_03:CONLL_03_GERMAN
embeddings:
  TransformerWordEmbeddings-0:
    fine_tune: true
    layers: '-1'
    model: roberta-large
    pooling_operation: first
interpolation: 0.5
is_teacher_list: true
model:
  FastSequenceTagger:
    crf_attention: false
    dropout: 0.0
    hidden_size: 256
    locked_dropout: 0.0
    sentence_loss: true
    use_cnn: false
    use_crf: false
    use_rnn: false
    word_dropout: 0.1
model_name: en-xlmr-first_10epoch_1batch_4accumulate_0.000005lr_10000lrrate_sem15res_monolingual_nocrf_fast_norelearn_sentbatch_sentloss_finetune_saving_nodev_semeval_ast6
ner:
  Corpus: CONLL_03_GERMAN
  professors:
    config/single-de-ner.yaml: CONLL_03_GERMAN
    config/single-en-ner.yaml: CONLL_03
    config/single-es-ner.yaml: CONLL_03_SPANISH
    config/single-nl-ner.yaml: CONLL_03_DUTCH
  tag_dictionary: resources/taggers/ner_tags.pkl
  teachers:
    ? config_gen/multi-bert_flair_word_char_charcnn_300epoch_32batch_0.1lr_256hidden_de_monolingual_nocrf_sentloss_10patience_fast_sentbatch_relearn_fasttext_freeze_nodev_panx_ner46.yaml
    : PANX-DE
    ? config_gen/multi-bert_flair_word_char_charcnn_300epoch_32batch_0.1lr_256hidden_es_monolingual_nocrf_sentloss_10patience_fast_sentbatch_relearn_fasttext_freeze_nodev_panx_ner45.yaml
    : PANX-ES
    ? config_gen/multi-bert_flair_word_char_charcnn_300epoch_32batch_0.1lr_256hidden_nl_monolingual_nocrf_sentloss_10patience_fast_sentbatch_relearn_fasttext_freeze_nodev_panx_ner47.yaml
    : PANX-NL
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_de_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_ner11.yaml
    : CONLL_03_GERMAN
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_en_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_ner11.yaml
    : CONLL_03
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_en_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_panx_ner6.yaml
    : PANX-EN
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_es_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_ner11.yaml
    : CONLL_03_SPANISH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_eu_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_panx_ner6.yaml
    : PANX-EU
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_fa_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_panx_ner8.yaml
    : PANX-FA
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_fr_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_panx_ner8.yaml
    : PANX-FR
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_he_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_panx_ner8.yaml
    : PANX-HE
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_id_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_panx_ner7.yaml
    : PANX-ID
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_nl_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_ner11.yaml
    : CONLL_03_DUTCH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_sl_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_panx_ner6.yaml
    : PANX-SL
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_ta_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_panx_ner6.yaml
    : PANX-TA
target_dir: resources/taggers/
targets: ast
teacher_annealing: false
train:
  embeddings_storage_mode: none
  fine_tune_mode: true
  gradient_accumulation_steps: 4
  learning_rate: 5.0e-06
  lr_rate: 10000
  max_epochs: 10
  mini_batch_size: 1
  monitor_test: false
  save_final_model: false
  save_finetuned_embedding: true
  train_with_dev: false
  true_reshuffle: false
  use_warmup: false
trainer: ModelFinetuner
upos:
  Corpus: UD_GERMAN:UD_ENGLISH:UD_FRENCH:UD_ITALIAN:UD_DUTCH:UD_SPANISH:UD_PORTUGUESE:UD_JAPANESE
  UD_GERMAN:
    train_config: config/
  professors:
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_de_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos0.yaml
    : UD_GERMAN
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_en_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos0.yaml
    : UD_ENGLISH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_es_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos0.yaml
    : UD_SPANISH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_fr_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_FRENCH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_it_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_ITALIAN
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_ja_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_JAPANESE
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_nl_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_DUTCH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_pt_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos0.yaml
    : UD_PORTUGUESE
  tag_dictionary: resources/taggers/pos_tags.pkl
  teachers:
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_de_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos0.yaml
    : UD_GERMAN
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_en_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos0.yaml
    : UD_ENGLISH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_es_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos0.yaml
    : UD_SPANISH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_fr_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_FRENCH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_it_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_ITALIAN
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_ja_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_JAPANESE
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_nl_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos1.yaml
    : UD_DUTCH
    ? config_gen/multi_bert_origflair_300epoch_2000batch_1lr_400hidden_pt_monolingual_nocrf_sentloss_10patience_baseline_fast_nodev_upos0.yaml
    : UD_PORTUGUESE
