ModelFinetuner:
  assign_doc_id: true
  distill_mode: false
  sentence_level_batch: true
  train_with_doc: true
anneal_factor: 2
embeddings:
  TransformerWordEmbeddings-0:
    fine_tune: true
    layers: '-1'
    model: xlnet-base-cased
    pooling_operation: first
    v2_doc: true
interpolation: 0.5
model:
  FastSequenceTagger:
    crf_attention: false
    dropout: 0.0
    hidden_size: 256
    locked_dropout: 0.0
    sentence_loss: true
    use_cnn: false
    use_crf: false
    use_rnn: false
    word_dropout: 0.1
model_name: test-xlnet-base-cased
ner:
  Corpus: ColumnCorpus-1
  ColumnCorpus-1: 
    data_folder: /home/wangxy/.flair/datasets/temp_dataset
    column_format:
      0: text
      1: pos
      2: chunk
      3: ner
    tag_to_bioes: ner
  tag_dictionary: ner_tags_harem.pkl
target_dir: resources/taggers/
targets: ner
train:
  embeddings_storage_mode: none
  fine_tune_mode: true
  gradient_accumulation_steps: 4
  learning_rate: 5.0e-06
  lr_rate: 10000
  max_epochs: 10
  mini_batch_size: 4
  monitor_test: false
  save_final_model: false
  save_finetuned_embedding: true
  train_with_dev: false
  true_reshuffle: false
  use_warmup: false
trainer: ModelFinetuner
